import Link from 'next/link';
import {ArrowUpRight,ArrowDown} from 'lucide-react';
import {Expertise,Team,Industries} from '@/components/experience';
import {CallToAction,Motion} from '@/components/site-chrome';
import {RotatingWord,Magnifier,StatsStrip,PlatformMarquee,ProcessScroll,GccNetwork} from '@/components/dynamic';
import {countries,insights} from '@/lib/content';
import {SiriWave} from '@/components/ui/siri-wave';
export default function Home(){return <main id="main">
<section className="hero"><div className="hero-copy"><span className="eyebrow">DUBAI ROOTS. GCC AMBITION.</span><h1>Strategy.<br/>Technology.<br/><RotatingWord/></h1><p>Good advice connects the dots.<br/>We connect business, marketing and technology<br className="desktop"/> to help your next chapter take shape.</p><div className="hero-actions"><Link className="button" href="/contact">Discuss your challenge <ArrowUpRight size={20}/></Link><a className="hero-discover" href="#expertise">Discover our expertise <ArrowDown size={16}/></a></div></div><div className="hero-visual"><div className="hero-scene"><img className="hero-base" src="/images/dubai.jpg" alt="Dubai skyline with the Burj Khalifa across the waterfront" width="2600" height="1463" fetchPriority="high"/><div className="hero-sky" aria-hidden="true"/><img className="hero-skyline" src="/images/dubai-skyline.webp" alt="" aria-hidden="true" width="2600" height="1463"/></div><div className="hero-image-caption"><span>25.2048° N / 55.2708° E</span><span>DUBAI, UAE</span></div><div className="hero-image-message"><span>Built on experience.<br/>Focused on what’s next.</span><ArrowUpRight size={43} strokeWidth={1}/></div></div></section>
<StatsStrip/>
<PlatformMarquee/>
<section className="section expertise-section" id="expertise"><div className="section-heading reveal"><span className="eyebrow">01 / CONNECTED EXPERTISE</span><h2>One team.<br/>The bigger picture.</h2><p>Business challenges rarely fit into one category. Neither do we. Our consultants bring strategy, marketing and technology together — from the first question to the work that follows.</p></div><div className="reveal" data-d="1"><Expertise/></div></section>
{/* Selected Work hidden until real client results are available — see CaseStudies in components/dynamic.tsx and lib/showcase.ts */}
<section className="about-band grain"><div className="reveal"><span className="eyebrow">GOOD STRATEGY DESERVES TO GO SOMEWHERE.</span><h2>From the<br/>boardroom<br/>to the real world.</h2></div><div className="reveal" data-d="1"><p>A strategy is only useful when people can act on it. We work alongside your teams to turn a clear direction into connected systems, stronger marketing and practical next steps.</p><Link className="text-link light" href="/about">Get to know Dan Gate <ArrowUpRight size={20}/></Link><div className="about-principles"><span>Direct access to experts</span><span>Strategy through to execution</span><span>Support shaped around your business</span></div></div></section>
<section className="section" id="consultants"><div className="section-heading compact reveal"><span className="eyebrow">02 / THE PEOPLE BEHIND THE WORK</span><h2>Experience, with<br/>a personal approach.</h2><div><p>Different perspectives. Complementary strengths. Work directly with the consultants doing the thinking.</p><Link className="text-link" href="/consultants">Meet the team <ArrowUpRight size={18}/></Link></div></div><div className="reveal" data-d="1"><Team/></div></section>
<section className="process-section section"><div className="process-layout"><div className="process-intro"><span className="eyebrow">03 / HOW WE WORK</span><h2>A clear path.<br/>A shared purpose.</h2><p>From understanding the challenge to making the next move. Every engagement starts with your business.</p></div><ProcessScroll/></div></section>
<section className="section industry-section"><div className="reveal"><span className="eyebrow">04 / YOUR BUSINESS, YOUR CONTEXT</span><h2>Expertise that<br/>adapts to you.</h2><p>Different customers. Different buying journeys. We shape our approach around the realities of your industry.</p><Link className="text-link" href="/industries">Explore industries <ArrowUpRight size={18}/></Link><div className="industry-wave" aria-hidden="true"><SiriWave variant="wave" transparent onLight coreColor="#075794" size={440} renderScale={1}/></div></div><div className="reveal" data-d="1"><Industries/></div></section>
<section className="gcc-band grain" id="gcc"><div className="reveal"><span className="eyebrow">ROOTED IN DUBAI. CONNECTED TO THE REGION.</span><h2>Ambition has<br/>no borders.</h2><Link className="text-link light" href="/gcc">Explore our GCC focus <ArrowUpRight size={20}/></Link></div><div className="reveal" data-d="1"><p>For businesses entering a new market, transforming operations or finding their next opportunity across the Gulf.</p><ul>{countries.map(c=><li key={c}>{c}<ArrowUpRight size={16}/></li>)}</ul></div></section><div className="gcc-map-band grain"><GccNetwork/></div>
<section className="section insights-section"><div className="section-title-line reveal"><div><span className="eyebrow">05 / PERSPECTIVES</span><h2>A little clarity.<br/>A better next step.</h2></div><Magnifier/><Link className="text-link" href="/insights">All insights <ArrowUpRight size={18}/></Link></div><div className="insight-grid">{insights.slice(0,3).map((item,i)=><Link className="insight-card reveal" data-d={i+1} href={'/insights/'+item.slug} key={item.slug}><div className="insight-top"><span className="eyebrow">{item.category}</span><span>0{i+1}</span></div><h3>{item.title}</h3><div className="insight-bottom"><span>Read perspective</span><ArrowUpRight size={22}/></div></Link>)}</div></section>
<CallToAction/><Motion/></main>}
