'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,Check} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {services,countries} from '@/lib/content';
import {consultationSchema} from '@/lib/consultation';
const empty={name:'',company:'',jobTitle:'',email:'',phone:'',country:'United Arab Emirates',service:'Not sure yet',challenge:'',website:''};
type Turnstile={render:(container:HTMLElement,options:{sitekey:string;action:string;callback:(token:string)=>void;'expired-callback':()=>void;'error-callback':()=>void})=>string;reset:(widgetId?:string)=>void;remove:(widgetId:string)=>void};
declare global{interface Window{turnstile?:Turnstile}}
export function ContactForm({siteKey}:{siteKey?:string}){const [values,setValues]=useState(()=>{if(typeof window==='undefined')return empty;const q=new URLSearchParams(window.location.search);const selected=q.get('service');const context=[q.get('consultant')&&'I would like to speak with '+q.get('consultant')+'.',q.get('industry')&&'My industry: '+q.get('industry')+'.',q.get('challenge')&&'I would like help with '+q.get('challenge')+'.'].filter(Boolean).join('\n');return{...empty,service:services.some(s=>s.title===selected)?selected!:'Not sure yet',challenge:context}});const[status,setStatus]=useState<'idle'|'sending'|'success'|'error'>('idle');const[error,setError]=useState('');const[reference,setReference]=useState('');const[turnstileToken,setTurnstileToken]=useState('');const requestId=useRef(typeof crypto==='undefined'?'':crypto.randomUUID());const formRef=useRef<HTMLFormElement>(null);const messageRef=useRef<HTMLDivElement>(null);const turnstileRef=useRef<HTMLDivElement>(null);const turnstileWidget=useRef<string | undefined>(undefined);
useEffect(()=>{if(!siteKey||!turnstileRef.current)return;const render=()=>{if(!window.turnstile||!turnstileRef.current||turnstileWidget.current)return;turnstileWidget.current=window.turnstile.render(turnstileRef.current,{sitekey:siteKey,action:'consultation',callback:token=>{setTurnstileToken(token);setError('');},'expired-callback':()=>setTurnstileToken(''),'error-callback':()=>{setTurnstileToken('');setError('The security check could not load. Please refresh the page and try again.');}})};const script=document.getElementById('cf-turnstile-script') as HTMLScriptElement|null;if(script){script.addEventListener('load',render);render();return()=>{script.removeEventListener('load',render);if(turnstileWidget.current)window.turnstile?.remove(turnstileWidget.current)}}const created=document.createElement('script');created.id='cf-turnstile-script';created.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';created.async=true;created.defer=true;created.addEventListener('load',render);document.head.appendChild(created);return()=>{created.removeEventListener('load',render);if(turnstileWidget.current)window.turnstile?.remove(turnstileWidget.current)}},[siteKey]);
useEffect(()=>{if(status==='success'||status==='error')messageRef.current?.focus()},[status]);
useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tool={name:'prepare_consultation',title:'Prepare a Dan Gate consultation',description:'Fill the visible consultation form for review. Does not submit or send the enquiry.',inputSchema:{type:'object',properties:{name:{type:'string'},company:{type:'string'},email:{type:'string'},challenge:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Expected form fields.');const data=input as Record<string,unknown>;const allowed=['name','company','email','challenge'];for(const[k,v]of Object.entries(data)){if(!allowed.includes(k)||typeof v!=='string'||v.length>(k==='challenge'?4000:254))throw new Error('Invalid field: '+k)}setValues(v=>({...v,...data}));setStatus('idle');setError('');return{status:'prepared',submitted:false}}};try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
async function submit(e:React.FormEvent){e.preventDefault();if(status==='sending')return;setError('');const parsed=consultationSchema.safeParse({...values,requestId:requestId.current,turnstileToken});if(!parsed.success){setError(parsed.error.issues[0].message);setStatus('error');return}setStatus('sending');try{const response=await fetch('/api/consultations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(parsed.data)});const result=await response.json() as {error?:string;reference:string};if(!response.ok)throw new Error(result.error||'Your enquiry could not be saved. Please try again.');setReference(result.reference);setStatus('success')}catch(err){setTurnstileToken('');if(turnstileWidget.current)window.turnstile?.reset(turnstileWidget.current);setError(err instanceof Error?err.message:'Please try again.');setStatus('error')}}
const change=(field:string,value:string)=>setValues(v=>({...v,[field]:value}));
if(status==='success')return <div className="form-success" tabIndex={-1} ref={messageRef} role="status"><Check size={34} color="#075794"/><h2>Your next chapter<br/>is on the table.</h2><p>Thank you, {values.name.split(' ')[0]}. Your consultation request has been saved for the Dan Gate team to review.</p><p className="reference">Your reference: {reference}</p><Link className="text-link" href="/services">Explore our expertise <ArrowUpRight size={18}/></Link></div>;
return <form ref={formRef} className="contact-form" onSubmit={submit} aria-label="Request a consultation"><div className="field full"><span className="eyebrow">TELL US ABOUT YOUR PROJECT</span></div>{[['name','Your name *','text','name'],['company','Company','text','organization'],['jobTitle','Job title','text','organization-title'],['email','Business email *','email','email'],['phone','Phone / WhatsApp','tel','tel']].map(([name,label,type,auto])=><div className="field" key={name}><label htmlFor={name}>{label}</label><Input id={name} name={name} type={type} autoComplete={auto} value={values[name as keyof typeof values]} onChange={e=>change(name,e.target.value)} required={['name','email'].includes(name)} maxLength={name==='email'?254:150}/></div>)}<div className="field"><label htmlFor="country">Country *</label><Select value={values.country} onValueChange={v=>change('country',v)}><SelectTrigger id="country" aria-label="Country"><SelectValue/></SelectTrigger><SelectContent>{[...countries,'Egypt','Other country'].map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></div><div className="field full"><label htmlFor="service">What can we help you with?</label><Select value={values.service} onValueChange={v=>change('service',v)}><SelectTrigger id="service" aria-label="What can we help you with?"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Not sure yet">Not sure yet — let’s explore</SelectItem>{services.map(s=><SelectItem value={s.title} key={s.slug}>{s.title}</SelectItem>)}</SelectContent></Select></div><div className="field full"><label htmlFor="challenge">Tell us about your challenge *</label><Textarea id="challenge" name="challenge" placeholder="What are you working towards, and what’s getting in the way?" value={values.challenge} onChange={e=>change('challenge',e.target.value)} required minLength={20} maxLength={4000}/></div><div className="hp-field" aria-hidden="true"><label htmlFor="website">Leave this field empty</label><input id="website" tabIndex={-1} autoComplete="off" value={values.website} onChange={e=>change('website',e.target.value)}/></div>{siteKey?<div className="field full"><span className="eyebrow">SECURITY CHECK</span><div ref={turnstileRef}/></div>:<div className="form-message" role="alert">The security check is not configured yet. Please try again later.</div>}<p className="form-note">* Required fields. We’ll use your details to understand and respond to your enquiry. <Link href="/privacy">How we handle your information.</Link></p>{error&&<div className="form-message" role="alert" tabIndex={-1} ref={messageRef}>{error}</div>}<div className="form-submit"><Button className="button" type="submit" disabled={status==='sending'||!siteKey||!turnstileToken}>{status==='sending'?'Saving your request…':'Request a consultation'}<ArrowUpRight size={20}/></Button></div></form>}
