'use client';
// Dynamic homepage pieces added in the redesign. Everything respects prefers-reduced-motion.
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight} from 'lucide-react';
import {processSteps,countries} from '@/lib/content';
import {stats,caseStudies} from '@/lib/showcase';
import {platformLogos} from '@/lib/platform-logos';

function useReducedMotion(){const[r,setR]=useState(false);useEffect(()=>{const m=window.matchMedia('(prefers-reduced-motion: reduce)');setR(m.matches);const f=()=>setR(m.matches);m.addEventListener('change',f);return()=>m.removeEventListener('change',f)},[]);return r}
function useInView<T extends Element>(threshold=.35){const ref=useRef<T>(null);const[seen,setSeen]=useState(false);useEffect(()=>{const el=ref.current;if(!el)return;const o=new IntersectionObserver(([e])=>{if(e.isIntersecting){setSeen(true);o.disconnect()}},{threshold});o.observe(el);return()=>o.disconnect()},[threshold]);return[ref,seen] as const}

/* ---------- Hero: rotating last word ---------- */
const words=['Growth.','Leads.','Revenue.','Reach.'];
export function RotatingWord(){const reduced=useReducedMotion();const[i,setI]=useState(0);useEffect(()=>{if(reduced)return;const t=setInterval(()=>setI(v=>(v+1)%words.length),2600);return()=>clearInterval(t)},[reduced]);return <span className="rotating-word" aria-label="Growth, leads, revenue, reach."><span key={i} className="rotating-word-inner" aria-hidden="true">{words[i]}</span></span>}

/* ---------- Hero: floating performance cards over the image ---------- */
export function HeroDashboard(){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const el=ref.current?.closest('.hero') as HTMLElement|null;if(!el||!window.matchMedia('(pointer:fine) and (prefers-reduced-motion: no-preference)').matches)return;const move=(e:PointerEvent)=>{const r=el.getBoundingClientRect();el.style.setProperty('--px',((e.clientX-r.left)/r.width-.5).toFixed(3));el.style.setProperty('--py',((e.clientY-r.top)/r.height-.5).toFixed(3))};el.addEventListener('pointermove',move);return()=>el.removeEventListener('pointermove',move)},[]);return <div className="hero-dash" ref={ref} aria-hidden="true"><div className="dash-card dash-card-a"><div className="dash-head"><span>Qualified leads</span><b>+142%</b></div><svg viewBox="0 0 200 64" className="dash-line"><defs><linearGradient id="dashFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#f15a22" stopOpacity=".35"/><stop offset="1" stopColor="#f15a22" stopOpacity="0"/></linearGradient></defs><path className="dash-area" d="M0 56 L22 50 L44 52 L66 40 L88 43 L110 30 L132 32 L154 18 L176 20 L200 6 L200 64 L0 64Z" fill="url(#dashFill)"/><path className="dash-stroke" d="M0 56 L22 50 L44 52 L66 40 L88 43 L110 30 L132 32 L154 18 L176 20 L200 6" fill="none" stroke="#f15a22" strokeWidth="2.5" strokeLinejoin="round" strokeLinecap="round" pathLength="1"/><circle className="dash-dot" cx="200" cy="6" r="4" fill="#f15a22"/></svg></div><div className="dash-card dash-card-b"><div className="dash-head"><span>ROAS</span><b>4.6×</b></div><div className="dash-bars">{[38,52,46,68,74,90].map((h,i)=><i key={i} style={{height:h+'%',animationDelay:(.9+i*.08)+'s'}}/>)}</div></div></div>}

/* ---------- Count-up number ---------- */
function CountUp({to,decimals=0,start}:{to:number;decimals?:number;start:boolean}){const reduced=useReducedMotion();const[v,setV]=useState(0);useEffect(()=>{if(!start)return;if(reduced){setV(to);return}let raf=0;const t0=performance.now();const d=1400;const tick=(t:number)=>{const p=Math.min(1,(t-t0)/d);setV(to*(1-Math.pow(1-p,3)));if(p<1)raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[start,to,reduced]);return <>{v.toFixed(decimals)}</>}

/* ---------- Stats strip ---------- */
export function StatsStrip(){const[ref,seen]=useInView<HTMLDivElement>(.4);return <section className="stats-strip" ref={ref} aria-label="Dan Gate in numbers">{stats.map(s=><div className="stat" key={s.label}><strong>{s.prefix}<CountUp to={s.value} start={seen}/>{s.suffix}</strong><span>{s.label}</span>{s.placeholder&&<em className="sample-tag">Sample</em>}</div>)}</section>}

/* ---------- Platforms marquee (logos) ---------- */
function brandColor(hex:string){const n=parseInt(hex.slice(1),16);const r=n>>16,g=(n>>8)&255,b=n&255;return (0.299*r+0.587*g+0.114*b)/255>0.72?'#332f3f':hex}
const featured=['Meta','Google Ads','Google Analytics','Google Tag Manager','HubSpot','Shopify','WordPress','TikTok','Snapchat','Zapier'];
const logos=platformLogos.filter(p=>featured.includes(p.name));
export function PlatformMarquee(){const row=[...logos,...logos,...logos,...logos];return <section className="marquee" aria-label="Platforms we work with"><span className="marquee-label">PLATFORMS WE WORK WITH</span><div className="marquee-track-wrap"><ul className="marquee-track">{row.map((p,i)=>{const dup=i>=logos.length;return <li key={i} aria-hidden={dup||undefined} title={p.name} style={{['--brand' as string]:brandColor(p.hex)}}><svg viewBox="0 0 24 24" role={dup?undefined:'img'} aria-label={dup?undefined:p.name} focusable="false"><path d={p.path}/></svg></li>})}</ul></div></section>}

/* ---------- Selected work ---------- */
export function CaseStudies(){const[ref,seen]=useInView<HTMLDivElement>(.25);return <div className="case-grid" ref={ref}>{caseStudies.map((c,i)=><article className="case-card reveal" data-d={i+1} key={c.title}><div className="case-top"><span className="eyebrow">{c.industry}</span>{c.placeholder&&<em className="sample-tag">Sample</em>}</div><div className="case-metric"><strong>{c.prefix}<CountUp to={c.metric} decimals={c.decimals} start={seen}/>{c.suffix}</strong><span>{c.metricLabel}</span></div><h3>{c.title}</h3><div className="case-compare"><span><small>Before</small>{c.before}</span><ArrowUpRight size={20}/><span><small>After</small>{c.after}</span></div><ul className="case-tags">{c.services.map(s=><li key={s}>{s}</li>)}</ul></article>)}</div>}

/* ---------- Scroll-driven process ---------- */
export function ProcessScroll(){const[active,setActive]=useState(0);const refs=useRef<(HTMLLIElement|null)[]>([]);useEffect(()=>{const o=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting)setActive(Number((e.target as HTMLElement).dataset.i))})},{rootMargin:'-45% 0px -45% 0px'});refs.current.forEach(el=>el&&o.observe(el));return()=>o.disconnect()},[]);const pct=((active+1)/processSteps.length)*100;return <div className="process-scroll"><div className="process-rail" aria-hidden="true"><div className="process-rail-fill" style={{height:pct+'%'}}/></div><ol>{processSteps.map((s,i)=><li key={s.title} data-i={i} ref={el=>{refs.current[i]=el}} className={i===active?'is-active':i<active?'is-done':''}><span className="process-step-no">0{i+1}</span><div><h3>{s.title}.</h3><p>{s.body}</p></div></li>)}</ol></div>}

/* ---------- GCC network map (stylised, full width) ---------- */
const hub={x:708,y:164};
const nodes:{c:string;city:string;x:number;y:number;up?:boolean}[]=[{c:'Saudi Arabia',city:'Riyadh',x:109,y:180},{c:'Qatar',city:'Doha',x:448,y:162},{c:'Kuwait',city:'Kuwait City',x:199,y:48,up:true},{c:'Bahrain',city:'Manama',x:382,y:135,up:true},{c:'Oman',city:'Muscat',x:928,y:209}];
export function GccNetwork(){const[ref,seen]=useInView<HTMLDivElement>(.3);return <div className={'gcc-network'+(seen?' is-live':'')} ref={ref}><svg viewBox="0 10 1000 250" role="img" aria-label={'Connections from Dubai to '+countries.slice(1).join(', ')}>{nodes.map((n,i)=>{const mx=(hub.x+n.x)/2,my=Math.max(6,Math.min(hub.y,n.y)-30-Math.abs(hub.x-n.x)*.1);const d=`M${hub.x} ${hub.y} Q${mx} ${my} ${n.x} ${n.y}`;return <g key={n.city}><path d={d} className="gcc-arc" pathLength="1" style={{transitionDelay:(i*.18)+'s'}}/><circle r="3.5" className="gcc-pulse-dot"><animateMotion dur={(2.8+i*.4)+'s'} repeatCount="indefinite" path={d} begin={(1+i*.2)+'s'}/></circle><circle cx={n.x} cy={n.y} r="6" className="gcc-node"/><circle cx={n.x} cy={n.y} r="6" className="gcc-ring" style={{animationDelay:(i*.3)+'s'}}/><text x={n.x} y={n.y+(n.up?-16:28)} textAnchor="middle">{n.city}</text></g>})}<circle cx={hub.x} cy={hub.y} r="10" className="gcc-hub"/><circle cx={hub.x} cy={hub.y} r="10" className="gcc-ring gcc-ring-hub"/><text x={hub.x} y={hub.y+34} textAnchor="middle" className="gcc-hub-label">Dubai</text></svg></div>}

/* ---------- Insights: animated magnifier ("a little clarity") ---------- */
const lensX='70;170;285;200;70',lensY='112;78;110;128;112';
function InsightChart(){const bars=[46,62,54,80,72,98,88,118];return <g><line x1="20" y1="170" x2="340" y2="170" stroke="#c9d1d8" strokeWidth="1.5"/>{bars.map((h,i)=><rect key={i} x={30+i*38} y={170-h} width="22" height={h} rx="2" fill={i===bars.length-1?'#f15a22':'#075794'} opacity={i===bars.length-1?1:.85}/>)}<polyline points="41,112 79,96 117,104 155,76 193,84 231,58 269,66 307,40" fill="none" stroke="#332f3f" strokeWidth="2.5" strokeLinejoin="round" strokeLinecap="round"/>{[[41,112],[155,76],[231,58],[307,40]].map(([x,y])=><circle key={x} cx={x} cy={y} r="4" fill="#fff" stroke="#332f3f" strokeWidth="2"/>)}</g>}
export function Magnifier(){return <div className="magnifier" aria-hidden="true"><svg viewBox="0 0 360 190"><defs><filter id="mgBlur"><feGaussianBlur stdDeviation="3.2"/></filter><clipPath id="mgClip"><circle cx="70" cy="112" r="40"><animate attributeName="cx" values={lensX} dur="9s" repeatCount="indefinite" calcMode="spline" keySplines=".45 0 .55 1;.45 0 .55 1;.45 0 .55 1;.45 0 .55 1"/><animate attributeName="cy" values={lensY} dur="9s" repeatCount="indefinite" calcMode="spline" keySplines=".45 0 .55 1;.45 0 .55 1;.45 0 .55 1;.45 0 .55 1"/></circle></clipPath></defs><g filter="url(#mgBlur)" opacity=".35"><InsightChart/></g><g clipPath="url(#mgClip)"><InsightChart/></g><g className="mg-lens"><animateTransform attributeName="transform" type="translate" values="70 112;170 78;285 110;200 128;70 112" dur="9s" repeatCount="indefinite" calcMode="spline" keySplines=".45 0 .55 1;.45 0 .55 1;.45 0 .55 1;.45 0 .55 1"/><circle r="40" fill="rgba(255,255,255,.08)" stroke="#332f3f" strokeWidth="5"/><path d="M-22 -18 A28 28 0 0 1 4 -30" fill="none" stroke="#fff" strokeWidth="4" strokeLinecap="round" opacity=".9"/><line x1="29" y1="29" x2="58" y2="58" stroke="#f15a22" strokeWidth="11" strokeLinecap="round"/></g></svg></div>}
