'use client';
// Dynamic homepage pieces added in the redesign. Everything respects prefers-reduced-motion.
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight} from 'lucide-react';
import {processSteps,countries} from '@/lib/content';
import {stats,platforms,caseStudies} from '@/lib/showcase';

function useReducedMotion(){const[r,setR]=useState(false);useEffect(()=>{const m=window.matchMedia('(prefers-reduced-motion: reduce)');setR(m.matches);const f=()=>setR(m.matches);m.addEventListener('change',f);return()=>m.removeEventListener('change',f)},[]);return r}
function useInView<T extends Element>(threshold=.35){const ref=useRef<T>(null);const[seen,setSeen]=useState(false);useEffect(()=>{const el=ref.current;if(!el)return;const o=new IntersectionObserver(([e])=>{if(e.isIntersecting){setSeen(true);o.disconnect()}},{threshold});o.observe(el);return()=>o.disconnect()},[threshold]);return[ref,seen] as const}

/* ---------- Hero: rotating last word ---------- */
const words=['Growth.','Leads.','Revenue.','Reach.'];
export function RotatingWord(){const reduced=useReducedMotion();const[i,setI]=useState(0);useEffect(()=>{if(reduced)return;const t=setInterval(()=>setI(v=>(v+1)%words.length),2600);return()=>clearInterval(t)},[reduced]);return <span className="rotating-word" aria-label="Growth, leads, revenue, reach."><span key={i} className="rotating-word-inner" aria-hidden="true">{words[i]}</span></span>}

/* ---------- Hero: floating performance cards over the image ---------- */
export function HeroDashboard(){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const el=ref.current?.closest('.hero') as HTMLElement|null;if(!el||!window.matchMedia('(pointer:fine) and (prefers-reduced-motion: no-preference)').matches)return;const move=(e:PointerEvent)=>{const r=el.getBoundingClientRect();el.style.setProperty('--px',((e.clientX-r.left)/r.width-.5).toFixed(3));el.style.setProperty('--py',((e.clientY-r.top)/r.height-.5).toFixed(3))};el.addEventListener('pointermove',move);return()=>el.removeEventListener('pointermove',move)},[]);return <div className="hero-dash" ref={ref} aria-hidden="true"><div className="dash-card dash-card-a"><div className="dash-head"><span>Qualified leads</span><b>+142%</b></div><svg viewBox="0 0 200 64" className="dash-line"><defs><linearGradient id="dashFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#f15a22" stopOpacity=".35"/><stop offset="1" stopColor="#f15a22" stopOpacity="0"/></linearGradient></defs><path className="dash-area" d="M0 56 L22 50 L44 52 L66 40 L88 43 L110 30 L132 32 L154 18 L176 20 L200 6 L200 64 L0 64Z" fill="url(#dashFill)"/><path className="dash-stroke" d="M0 56 L22 50 L44 52 L66 40 L88 43 L110 30 L132 32 L154 18 L176 20 L200 6" fill="none" stroke="#f15a22" strokeWidth="2.5" strokeLinejoin="round" strokeLinecap="round" pathLength="1"/><circle className="dash-dot" cx="200" cy="6" r="4" fill="#f15a22"/></svg></div><div className="dash-card dash-card-b"><div className="dash-head"><span>ROAS</span><b>4.6×</b></div><div className="dash-bars">{[38,52,46,68,74,90].map((h,i)=><i key={i} style={{height:h+'%',animationDelay:(.9+i*.08)+'s'}}/>)}</div></div></div>}

/* ---------- Count-up number ---------- */
function CountUp({to,decimals=0,start}:{to:number;decimals?:number;start:boolean}){const reduced=useReducedMotion();const[v,setV]=useState(0);useEffect(()=>{if(!start)return;if(reduced){setV(to);return}let raf=0;const t0=performance.now();const d=1400;const tick=(t:number)=>{const p=Math.min(1,(t-t0)/d);setV(to*(1-Math.pow(1-p,3)));if(p<1)raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[start,to,reduced]);return <>{v.toFixed(decimals)}</>}

/* ---------- Stats strip ---------- */
export function StatsStrip(){const[ref,seen]=useInView<HTMLDivElement>(.4);return <section className="stats-strip" ref={ref} aria-label="Dan Gate in numbers">{stats.map(s=><div className="stat" key={s.label}><strong>{s.prefix}<CountUp to={s.value} start={seen}/>{s.suffix}</strong><span>{s.label}</span>{s.placeholder&&<em className="sample-tag">Sample</em>}</div>)}</section>}

/* ---------- Platforms marquee ---------- */
export function PlatformMarquee(){const row=[...platforms,...platforms];return <section className="marquee" aria-label="Platforms we work with"><span className="marquee-label">PLATFORMS WE WORK WITH</span><div className="marquee-track-wrap"><ul className="marquee-track">{row.map((p,i)=><li key={i} aria-hidden={i>=platforms.length}>{p}<i/></li>)}</ul></div></section>}

/* ---------- Selected work ---------- */
export function CaseStudies(){const[ref,seen]=useInView<HTMLDivElement>(.25);return <div className="case-grid" ref={ref}>{caseStudies.map((c,i)=><article className="case-card reveal" data-d={i+1} key={c.title}><div className="case-top"><span className="eyebrow">{c.industry}</span>{c.placeholder&&<em className="sample-tag">Sample</em>}</div><div className="case-metric"><strong>{c.prefix}<CountUp to={c.metric} decimals={c.decimals} start={seen}/>{c.suffix}</strong><span>{c.metricLabel}</span></div><h3>{c.title}</h3><div className="case-compare"><span><small>Before</small>{c.before}</span><ArrowUpRight size={20}/><span><small>After</small>{c.after}</span></div><ul className="case-tags">{c.services.map(s=><li key={s}>{s}</li>)}</ul></article>)}</div>}

/* ---------- Scroll-driven process ---------- */
export function ProcessScroll(){const[active,setActive]=useState(0);const refs=useRef<(HTMLLIElement|null)[]>([]);useEffect(()=>{const o=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting)setActive(Number((e.target as HTMLElement).dataset.i))})},{rootMargin:'-45% 0px -45% 0px'});refs.current.forEach(el=>el&&o.observe(el));return()=>o.disconnect()},[]);const pct=((active+1)/processSteps.length)*100;return <div className="process-scroll"><div className="process-rail" aria-hidden="true"><div className="process-rail-fill" style={{height:pct+'%'}}/></div><ol>{processSteps.map((s,i)=><li key={s.title} data-i={i} ref={el=>{refs.current[i]=el}} className={i===active?'is-active':i<active?'is-done':''}><span className="process-step-no">0{i+1}</span><div><h3>{s.title}.</h3><p>{s.body}</p></div></li>)}</ol></div>}

/* ---------- GCC network map ---------- */
const hub={x:345,y:116};
const nodes:{c:string;city:string;x:number;y:number;up?:boolean}[]=[{c:'Saudi Arabia',city:'Riyadh',x:174,y:126},{c:'Qatar',city:'Doha',x:271,y:114},{c:'Kuwait',city:'Kuwait City',x:199,y:33,up:true},{c:'Bahrain',city:'Manama',x:252,y:95,up:true},{c:'Oman',city:'Muscat',x:408,y:148}];
export function GccNetwork(){const[ref,seen]=useInView<HTMLDivElement>(.3);return <div className={'gcc-network'+(seen?' is-live':'')} ref={ref}><svg viewBox="0 0 440 200" role="img" aria-label={'Connections from Dubai to '+countries.slice(1).join(', ')}><defs><pattern id="gccDots" width="10" height="10" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1" fill="#ffffff" opacity=".14"/></pattern></defs><rect width="440" height="200" fill="url(#gccDots)"/>{nodes.map((n,i)=>{const mx=(hub.x+n.x)/2,my=Math.min(hub.y,n.y)-40-Math.abs(hub.x-n.x)*.12;const d=`M${hub.x} ${hub.y} Q${mx} ${my} ${n.x} ${n.y}`;return <g key={n.city}><path d={d} className="gcc-arc" pathLength="1" style={{transitionDelay:(i*.18)+'s'}}/><circle r="2.6" className="gcc-pulse-dot"><animateMotion dur={(2.6+i*.4)+'s'} repeatCount="indefinite" path={d} begin={(1+i*.2)+'s'}/></circle><circle cx={n.x} cy={n.y} r="4" className="gcc-node"/><circle cx={n.x} cy={n.y} r="4" className="gcc-ring" style={{animationDelay:(i*.3)+'s'}}/><text x={n.x} y={n.y+(n.up?-11:19)} textAnchor="middle">{n.city}</text></g>})}<circle cx={hub.x} cy={hub.y} r="7" className="gcc-hub"/><circle cx={hub.x} cy={hub.y} r="7" className="gcc-ring gcc-ring-hub"/><text x={hub.x} y={hub.y+24} textAnchor="middle" className="gcc-hub-label">Dubai</text></svg></div>}
