'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,Plus,ArrowRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {services,groups,consultants,processSteps,industries} from '@/lib/content';
export function Expertise({full=false}:{full?:boolean}){return <Tabs defaultValue={groups[0]} className="expertise-tabs"><TabsList aria-label="Expertise categories" className="expertise-tablist">{groups.map((g,i)=><TabsTrigger value={g} key={g}><span>0{i+1}</span>{g}</TabsTrigger>)}</TabsList>{groups.map(g=><TabsContent key={g} value={g}><Accordion type="single" collapsible className="service-accordion">{services.filter(s=>s.group===g).map((s,i)=><AccordionItem value={s.slug} key={s.slug}><AccordionTrigger className="service-trigger"><span className="service-index">0{i+1}</span><span>{s.title}</span></AccordionTrigger><AccordionContent><div className="service-expanded"><p>{s.description}</p><div><ul>{s.items.slice(0,full?6:3).map(item=><li key={item}>{item}</li>)}</ul><Link className="text-link" href={'/services/'+s.slug}>Explore {s.title.toLowerCase()} <ArrowUpRight size={18}/></Link></div></div></AccordionContent></AccordionItem>)}</Accordion></TabsContent>)}</Tabs>}
export function Team({detailed=false}:{detailed?:boolean}){const[selected,setSelected]=useState<number|null>(null);return <><div className={'team-grid '+(detailed?'team-detailed':'')}>{consultants.map((p,i)=><article className="person" key={p.name}><button className="person-photo" onClick={()=>setSelected(i)} aria-label={'Meet '+p.name}><img src={'/images/'+p.photo} alt={`${p.name} - ${p.role} at Dan Gate Consultancy Dubai`} loading="lazy" width="700" height="800"/><span className="person-plus"><Plus size={24}/></span></button><div className="person-heading"><h3>{p.name}</h3><span>0{i+1}</span></div><p className="person-role">{p.role}</p>{detailed&&<><p className="person-summary">{p.summary}</p><ul className="tags">{p.expertise.map(e=><li key={e}>{e}</li>)}</ul></>}</article>)}</div><Dialog open={selected!==null} onOpenChange={o=>{if(!o)setSelected(null)}}><DialogContent className="profile-dialog">{selected!==null&&<><img src={'/images/'+consultants[selected].photo} alt={`${consultants[selected].name} - ${consultants[selected].role}`}/><div><span className="eyebrow">MEET YOUR CONSULTANT</span><DialogTitle>{consultants[selected].name}</DialogTitle><DialogDescription>{consultants[selected].role}</DialogDescription><p>{consultants[selected].summary}</p><ul className="tags">{consultants[selected].expertise.map(e=><li key={e}>{e}</li>)}</ul><Link className="text-link" href={'/contact?consultant='+encodeURIComponent(consultants[selected].name)}>Start a conversation <ArrowUpRight size={18}/></Link></div></>}</DialogContent></Dialog></>}
export function Process(){return <Tabs defaultValue="0" className="process-tabs"><TabsList aria-label="Our consulting process" className="process-list">{processSteps.map((s,i)=><TabsTrigger value={String(i)} key={s.title}><span>0{i+1}</span>{s.title}</TabsTrigger>)}</TabsList>{processSteps.map((s,i)=><TabsContent value={String(i)} key={s.title}><div className="process-content"><span className="process-number">0{i+1}</span><div><h3>{s.title}.</h3><p>{s.body}</p></div><ArrowRight className="process-arrow" size={64} strokeWidth={1}/></div></TabsContent>)}</Tabs>}
export function Industries(){return <Accordion type="single" collapsible defaultValue="Real Estate" className="industry-accordion">{industries.map((item,i)=><AccordionItem value={item.title} key={item.title}><AccordionTrigger><span className="service-index">0{i+1}</span><span>{item.title}</span></AccordionTrigger><AccordionContent><p>{item.body}</p><ul className="tags">{item.services.map(s=><li key={s}>{s}</li>)}</ul><Link className="text-link" href={'/contact?industry='+encodeURIComponent(item.title)}>Discuss your business <ArrowUpRight size={18}/></Link></AccordionContent></AccordionItem>)}</Accordion>}
