'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useState} from 'react';
import {ArrowUpRight, Menu} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription,SheetTrigger,SheetClose} from '@/components/ui/sheet';
import {Button} from '@/components/ui/button';
const links=[['Our expertise','/services'],['About us','/about'],['Our consultants','/consultants'],['GCC','/gcc'],['Insights','/insights']];
export function Header(){const path=usePathname();const[open,setOpen]=useState(false);useEffect(()=>setOpen(false),[path]);return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><Link href="/" className="brand" aria-label="Dan Gate home"><img src="/images/dan-gate.png" alt="" width="63" height="61"/><span>DAN GATE<small>STRATEGY. TECHNOLOGY. GROWTH.</small></span></Link><nav aria-label="Main navigation">{links.map(([label,href])=><Link key={href} href={href} aria-current={path===href?'page':undefined}>{label}</Link>)}</nav><div className="header-actions"><Link className="button button-small" href="/contact">Let’s talk <ArrowUpRight size={17}/></Link><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><Button variant="ghost" size="icon" className="mobile-toggle" aria-label="Open menu"><Menu/></Button></SheetTrigger><SheetContent className="mobile-nav"><SheetTitle>Dan Gate</SheetTitle><SheetDescription>Strategy. Technology. Growth.</SheetDescription><nav aria-label="Mobile navigation">{[['Home','/'],...links,['Industries','/industries'],['Contact','/contact']].map(([label,href])=><SheetClose asChild key={href}><Link href={href}>{label}<ArrowUpRight size={18}/></Link></SheetClose>)}</nav></SheetContent></Sheet></div></header></>}
export function Footer(){return <footer className="site-footer"><div className="footer-top"><Link className="footer-brand" href="/">DAN GATE<span>Strategy. Technology. Growth.</span></Link><p>Independent thinking.<br/>Connected expertise.<br/>Dubai, United Arab Emirates.</p><div><span className="eyebrow">EXPLORE</span><Link href="/services">Our expertise</Link><Link href="/industries">Industries</Link><Link href="/gcc">Across the GCC</Link></div><div><span className="eyebrow">DAN GATE</span><Link href="/about">About us</Link><Link href="/consultants">Our consultants</Link><Link href="/insights">Insights</Link><Link href="/contact">Get in touch <ArrowUpRight size={15}/></Link></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Dan Gate. All rights reserved.</span><Link href="/privacy">Privacy</Link><span>BUSINESS + MARKETING + TECHNOLOGY</span></div></footer>}
export function CallToAction(){return <section className="cta-section"><div><span className="eyebrow">YOUR NEXT CHAPTER STARTS WITH A CONVERSATION</span><h2>What’s your<br/><span>next move?</span></h2></div><div><p>You don’t need to have the solution figured out. Tell us what you’re trying to achieve. We’ll start there.</p><Link className="button shake-on-view" href="/contact">Discuss your challenge <ArrowUpRight size={20}/></Link></div></section>}
export function Motion(){const path=usePathname();useEffect(()=>{const root=document.documentElement;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;const cleanups:(()=>void)[]=[];if(!reduced){root.classList.add('motion-ready');const observer=new IntersectionObserver((entries)=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');observer.unobserve(e.target)}})},{threshold:.12,rootMargin:'0px 0px -6% 0px'});document.querySelectorAll('.reveal:not(.in-view)').forEach(el=>observer.observe(el));cleanups.push(()=>observer.disconnect());const shaker=new IntersectionObserver((entries)=>{entries.forEach(e=>{e.target.classList.toggle('shake',e.isIntersecting)})},{threshold:1});document.querySelectorAll('.shake-on-view').forEach(el=>shaker.observe(el));cleanups.push(()=>shaker.disconnect())}
if(!reduced&&window.matchMedia('(pointer:fine)').matches){document.querySelectorAll<HTMLElement>('.button').forEach(b=>{const move=(e:PointerEvent)=>{const r=b.getBoundingClientRect();const x=(e.clientX-r.left-r.width/2)*.22;const y=(e.clientY-r.top-r.height/2)*.3;b.style.transform=`translate(${x}px,${y}px)`};const leave=()=>{b.style.transform=''};b.addEventListener('pointermove',move);b.addEventListener('pointerleave',leave);cleanups.push(()=>{b.removeEventListener('pointermove',move);b.removeEventListener('pointerleave',leave);b.style.transform=''})})}
return()=>cleanups.forEach(f=>f())},[path]);return null}
