export type Service = {slug:string;title:string;group:string;description:string;items:string[];consultant:number};
export const groups = ['Business strategy', 'Marketing & growth', 'Technology & digital'];
export const services:Service[] = [
{slug:'marketing-strategy',title:'Marketing Strategy',group:groups[0],description:'Build a clear marketing direction based on your business objectives, market opportunities, customer needs and competitive environment.',items:['Marketing strategy','Market and competitor analysis','Positioning','Customer and audience strategy','Channel strategy','Campaign planning','Marketing performance frameworks','Marketing transformation'],consultant:1},
{slug:'business-development',title:'Business Development',group:groups[0],description:'Identify opportunities and create practical strategies to support commercial growth.',items:['Business development strategy','Market opportunity analysis','Growth planning','Partnership opportunities','Go-to-market planning','Commercial strategy','Lead-generation strategy'],consultant:1},
{slug:'digital-transformation',title:'Digital Transformation',group:groups[0],description:'Transform how your organization uses technology, data and digital processes.',items:['Digital transformation strategy','Digital maturity assessment','Transformation roadmaps','Process improvement','Customer journey transformation','Technology planning','Digital operating models','Change and adoption planning'],consultant:0},
{slug:'digital-marketing',title:'Digital Marketing Strategy',group:groups[1],description:'Build an integrated digital marketing strategy that connects channels, audiences, content and conversion.',items:['Digital marketing strategy','Lead-generation strategy','Search strategy','Social media strategy','Paid media','Content strategy','Conversion optimization','Analytics and measurement'],consultant:0},
{slug:'seo',title:'SEO Consulting',group:groups[1],description:'Build sustainable organic visibility and capture demand from customers actively searching for your products or services.',items:['SEO strategy','Technical SEO','On-page SEO','Keyword research','Content strategy','Local SEO','International and GCC SEO','Competitor analysis','SEO audits','Organic performance measurement'],consultant:2},
{slug:'media-buying',title:'Media Buying',group:groups[1],description:'Turn paid media investment into a structured, measurable acquisition engine.',items:['Media strategy','Channel selection','Audience strategy','Campaign structure','Budget allocation','Lead-generation campaigns','Performance optimization','Tracking and attribution','Media performance analysis'],consultant:2},
{slug:'pr-strategy',title:'PR Strategy & Monitoring',group:groups[1],description:'Build a structured approach to communications, media relationships and brand visibility.',items:['PR strategy','Communications planning','Media strategy','Messaging','PR monitoring','Media coverage analysis','Reputation monitoring','Campaign measurement'],consultant:1},
{slug:'crm-integrations',title:'CRM Consulting & Integration',group:groups[2],description:'Turn your CRM into a connected business platform, bringing customers, sales and marketing into one clearer picture.',items:['CRM strategy','CRM implementation planning','CRM integrations','Lead management','Customer journey design','Marketing and sales integration','CRM data structure','Reporting and dashboards','CRM optimization'],consultant:0},
{slug:'automation',title:'Automation',group:groups[2],description:'Connect systems and automate repetitive processes to improve efficiency and reduce manual work.',items:['Workflow automation','Lead automation','Marketing automation','CRM automation','Data synchronization','Notifications and workflows','Platform integrations','Process optimization'],consultant:0},
{slug:'systems-integration',title:'Tools & Systems Integration',group:groups[2],description:'Connect the platforms your organization already uses, so information moves where it is needed.',items:['CRM and marketing integration','Website and advertising platforms','Analytics and communication platforms','Data flow and process integration','Integration strategy'],consultant:2},
{slug:'web-technology',title:'Web Technology Strategy',group:groups[2],description:'Make sure your website and digital platforms are built around business requirements, customer experience and future scalability.',items:['Website technology strategy','Platform selection','Technical architecture','Website transformation','CMS strategy','Third-party integrations','Analytics implementation','Performance and scalability'],consultant:2},
{slug:'ai-solutions',title:'AI Solutions & Development',group:groups[2],description:'Use AI where it can create practical business value, from useful workflows to faster digital development.',items:['AI opportunity assessment','AI-powered workflows','AI automation','AI-assisted development','Rapid prototyping','Internal productivity solutions','AI tools integration','AI adoption strategy'],consultant:2},
{slug:'training-workshops',title:'Training & Workshops',group:groups[2],description:'Build your internal digital capabilities through practical training and workshops.',items:['Digital transformation','CRM','Automation','Digital marketing','SEO','AI and modern digital tools','Marketing strategy','Digital operations'],consultant:0}
];
export const consultants=[
{name:'Ahmed Atef',role:'Digital Transformation & CRM Consultant',photo:'ahmed-atef.webp',summary:'Ahmed connects business objectives with technology, customer data and practical digital processes. He works across digital transformation, CRM integration, automation and digital marketing strategy.',expertise:['Digital Transformation','CRM Strategy & Integration','Business Automation','Digital Marketing Strategy','Digital Process Optimization','Training & Workshops']},
{name:'Mahmoud Rashad',role:'Marketing & Business Development Consultant',photo:'mahmoud-rashad.webp',summary:'Mahmoud helps organizations connect market opportunities with practical commercial and communication strategies. His work spans marketing strategy, business development and PR strategy and monitoring.',expertise:['Marketing Strategy','Business Development','Growth Strategy','PR Strategy','PR Monitoring','Communications Planning']},
{name:'Ihab Mohsen',role:'Web Technology, SEO & AI Consultant',photo:'consultant-portrait.webp',summary:'Ihab helps organizations strengthen the technology and acquisition infrastructure behind their digital growth, with expertise in web technology, SEO, media buying, tools integration and AI-assisted development.',expertise:['Web Technology Strategy','SEO','Media Buying','Tools & Platform Integration','AI Solutions','AI-Assisted Development']}
];
export const processSteps=[
{title:'Discover',body:'We understand your business, objectives, customers, existing systems and current challenges.'},
{title:'Strategize',body:'We identify opportunities and build a clear roadmap aligned with your priorities.'},
{title:'Connect',body:'We bring together the right technology, platforms, data, processes and marketing channels.'},
{title:'Execute',body:'We support implementation and help turn recommendations into practical initiatives.'},
{title:'Optimize',body:'We measure performance, identify opportunities and continuously improve.'}
];
export const industries=[
{title:'Real Estate',body:'Improve digital lead generation, CRM, customer journeys, SEO, paid media and marketing performance.',services:['CRM & customer journeys','Lead generation','Search & paid media']},
{title:'Professional Services',body:'Build stronger positioning, lead generation, business development and digital presence.',services:['Positioning & strategy','Business development','Digital presence']},
{title:'Retail & E-commerce',body:'Connect marketing, technology, customer experience, SEO, paid media and automation.',services:['Customer experience','E-commerce technology','Marketing automation']},
{title:'Technology & Startups',body:'Develop go-to-market strategies, digital platforms, SEO, AI solutions and scalable growth systems.',services:['Go-to-market planning','Digital platforms','AI & growth systems']},
{title:'Corporate & Enterprise',body:'Support digital transformation, CRM, technology integration, automation and internal capability development.',services:['Digital transformation','Systems integration','Training & adoption']}
];
export const countries=['United Arab Emirates','Saudi Arabia','Qatar','Kuwait','Bahrain','Oman'];
export const insights=[
{slug:'digital-transformation',category:'DIGITAL TRANSFORMATION',title:'Start with the business. Then choose the technology.',intro:'A useful transformation roadmap begins with the way your organization works today.',paragraphs:['Before choosing a new platform, map the business problem it needs to solve. Where do customers face friction? Where do teams repeat work? Which decisions are held back by missing information?','Prioritize a small set of improvements with clear owners and measurable outcomes. A faster lead response or a simpler approval process can be a more useful starting point than a broad list of technology upgrades.','Plan for adoption alongside implementation. Give people time to learn, agree who owns the process and review whether the change is helping the business.'],service:'digital-transformation'},
{slug:'crm-automation',category:'CRM & AUTOMATION',title:'A connected CRM starts with a clear customer journey.',intro:'Useful customer data depends on clear processes as much as connected platforms.',paragraphs:['Follow a customer from first enquiry through qualification, sales and ongoing service. Identify where information is captured, who needs it and where it gets lost between teams.','Agree on the meaning of each stage before automating it. Shared definitions for a qualified lead, an active opportunity and a completed handover make reporting easier to trust.','Start with a workflow that removes a recurring delay. Test the handover, check the data and give the team a way to handle exceptions before adding further automation.'],service:'crm-integrations'},
{slug:'marketing-growth',category:'MARKETING & GROWTH',title:'Acquisition works better when the whole journey works.',intro:'Campaigns, websites and sales teams all shape what happens after the first click.',paragraphs:['Look beyond traffic when assessing marketing performance. The questions visitors ask, the clarity of an offer and the quality of a follow-up all influence whether interest becomes a meaningful enquiry.','Connect channel reporting with the stages of your sales process. Review which sources produce useful conversations and where promising leads stop progressing.','Choose the next improvement based on the weakest part of the journey. That might be clearer positioning, a more relevant landing page, better tracking or a faster response from the team.'],service:'marketing-strategy'},
{slug:'seo-search',category:'SEO & SEARCH',title:'Build visibility around the questions customers actually ask.',intro:'An effective search strategy connects useful content with a website people can navigate.',paragraphs:['Start with the language customers use to describe their needs. Group related questions around services, use cases and decisions rather than creating a page for every keyword variation.','Make the important pages easy to find and understand. Clear navigation, useful headings and relevant internal links help visitors move from research to action.','Review search visibility alongside enquiry quality. Use what you learn to improve existing pages and identify gaps that deserve genuinely useful new content.'],service:'seo'},
{slug:'technology-ai',category:'TECHNOLOGY & AI',title:'Find a useful job for AI before choosing a tool.',intro:'A practical starting point is a defined task, a clear owner and a way to check the output.',paragraphs:['List recurring tasks that take time and have a clear definition of success. Consider where assistance with a draft, a summary or a repeatable workflow could help the team.','Decide what information the workflow needs and who should have access to it. Keep a person responsible for reviewing outputs that affect customers or important business decisions.','Try a bounded pilot and compare the result with the existing process. Assess time saved, output quality and the effort required to maintain the workflow before expanding it.'],service:'ai-solutions'},
{slug:'business-development',category:'BUSINESS DEVELOPMENT',title:'Turn a market opportunity into a practical next move.',intro:'A growth plan becomes useful when it connects an opportunity to a specific customer need.',paragraphs:['Define the customer, the problem and the reason your business can help. A clear proposition makes it easier to assess whether a new market or partnership fits your capabilities.','Identify what needs to be true for the opportunity to work. Consider the route to customers, the sales process, delivery capacity and the relationships you will need to build.','Choose a focused first initiative with an owner and a review point. Use the evidence from early conversations and delivery to refine the plan.'],service:'business-development'}
];
